### ISSUE TITLE
[question] Does it works with Audio Source from mic?

### ISSUE THREAD

**Issue by KestutisMa** [bastibl/gnuradio-android#1]
Does it works with Audio Source (from mic) and Audio Sink?

**Comment by bastibl** [comment]
The normal audio sources/sinks from GNU Radio do not work. But it supports [gr-grand](https://github.com/bastibl/gr-grand) which provides Android versions. The FM receiver app, for example, uses the the audio sink:

https://www.youtube.com/watch?v=8ReyVzUyppA
