### ISSUE TITLE
Missing .so file on armeabi-v7a

### ISSUE THREAD

**Issue by ojshss** [bastibl/gnuradio-android#10]
Error when building apk for armeabi-v7a cpu architecture, missing libuhd.so and libgnuradio-uhd.so. On the other hand, building using arm64-v8a no error occurred.
![error](https://user-images.githubusercontent.com/51981021/118654529-3e131d80-b81b-11eb-98b9-7d2fb34d2a63.png)

**Comment by bastibl** [comment]
Maybe you only ran `build_aarch64.sh` but not `build.sh`? If so, did the latter run without errors?

**Comment by ojshss** [comment]
Yes arm64 build variant build successfully. Unfortunately armeabi-v7a  have missing .so files. I run again the build.sh and still same missing .so file when building the project on armeabi build variant. Attached file are the libs of arm64 and armeabi folders.
![toolchain files of armeabi-v7a](https://user-images.githubusercontent.com/51981021/118914326-9baf8300-b95d-11eb-99a7-b7291efa56b1.png)
![toolchain files of arm64-v8a](https://user-images.githubusercontent.com/51981021/118914331-9ce0b000-b95d-11eb-8da3-63bfeac7f098.png)

**Comment by ojshss** [comment]
libgnuradio-uhd.so and libuhd.so were missing on armeabi-v7a lib folder which are needed during building the project.

**Comment by bastibl** [comment]
I just noticed that uhd is not built for `armeabi-v7a`. If you really need uhd support for this architecture, you'd have to add it to the build script. See the `aarch64` version. It probably just works by copying over the relevant sections with trivial modifications.
If you add it to the build, a PR would be very much appreciated.

**Comment by rustyshackelford221** [comment]
did the op resolve the issue? ive copied over the libuhd.so and the libgnuradio-uhd.so files and a couple others, but another error shows up saying "cant find  -luhd".  I can't find this files in the arm64-v8a builds either, please help?

**Comment by bastibl** [comment]
Sorry, but I don't understand a thing. You copied some files, but the files don't exist? And then something tries to link with -luhd, but what is not clear. You'd have to add much more information.

**Comment by rustyshackelford221** [comment]
my bad the android-studio concept is new to me, but i copied the files as suggested from the previous post, from arm64 toolchain build to the armeabi-v7a toolchain build.  However when i click run app it still comes across an error that it could not find "-luhd", and wont build any further.  I apologize if it comes across as a bit confusing but its all a bit confusing to me as well as i am learning on the fly.

**Comment by bastibl** [comment]
You cannot copy aarch64 file to armv7. This was also not suggested in previous post, which referred to extend the armv7 build script to also build uhd for the platform. If you don't build uhd for amv7, you cannot link against them. Apart from this, there are probably issues with you cmake script. The projects linked in the readme use absolute paths. If the file is there, it should at least be found (raising an error, if it was compiled for another architecture). Again, if you want help please open a separate issue, with much much more information. This is very vague.
