### ISSUE TITLE
Latest master dockerfile does not build

### ISSUE THREAD

**Issue by marcospanghero** [bastibl/gnuradio-android#11]
Hi,
The lastest and greatest master docker file seems to be not building. The andoid NDK version specified in the Dockerfile is 20.0.5594570 while the TOOLCHAIN_ROOT in build.sh and build_aarch64.sh point to 21.3.6528147

Am I doing something wrong?

changing the version of ndk in Dockerfile to 21.3.6528147 allows building continue after the exports in build.sh but still does not build correctly

**Comment by bastibl** [comment]
Arg, I don't use Docker and forgot to update the NDK version. Would you mind submitting a PR for the fixed Dockerfile?

**Comment by marcospanghero** [comment]
I spent some hours testing last night and managed to get the full docker to build. Seems that there are issues with the apps too. The apps in the git were build with the previous version of NDK/Tools/Cmake so this is an issue later when they are loaded in android studio. 
I feel like that there are still some issues as the app builds and can be loaded on the mobile phone but still crashes straight away. I will investigate but do you have any ideas?

I will make a PR for the Dockerfile later today, no problem. #12

**Comment by bastibl** [comment]
Thanks for the PR!

Regarding the issues with applications: For prior updates, Android Studio offered quick fixes for version changes that just worked. If there are problems with the applications, can you tell me which you are trying and what happens?
Maybe the application expects firmware images or configuration files to be present or similar. You can check the log output to get more information about the crash.

**Comment by marcospanghero** [comment]
Further investigation showed the issue. Apparently in the gradle cmake argument the cflag cannot c++11 but needs to be modified to -DANDROID_STL=c++_shared.

I will investigate more if this works or not before making a PR
