### ISSUE TITLE
successfull build but runtime Error: missing .so

### ISSUE THREAD

**Issue by mohsenD98** [bastibl/gnuradio-android#16]
hi **thanks** for your grate work.

i am working on radio-FM project. i build it exactly based on the tutorial .. i installed it too. but i got this error: 
![image](https://user-images.githubusercontent.com/36326627/222831251-dbb86281-6581-407c-9513-56155911cb85.png)

when i comment this line: 

![image](https://user-images.githubusercontent.com/36326627/222831333-436861f9-2f2a-41d5-9f8b-12cae0f3c658.png)

its working and enters to app .. but obviously its not working ...
so why it cannot find *.so files to load library?

**Comment by MidnightCoder-m** [comment]
i am running on Samsung A30

**Comment by MidnightCoder-m** [comment]
i find out my mistake... 
i compiled every thing with ndk  21.3.6528147 but in `build.gradel(:app)`  it was your ndk.. so this error means there is problem with JniLibs.
