### ISSUE TITLE
 Prebuild Dependency in build.gradle

### ISSUE THREAD

**Issue by ne1** [bastibl/gnuradio-android#4]
Hi,

in the new Version from Android Studio there is a change in jniLibs.

https://developer.android.com/studio/releases/gradle-plugin#cmake-imported-targets

After performing the Upgrade the App will not compile anymore:

`More than one file was found with OS independent path 'lib/arm64-v8a/libuhd.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/previev/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake`

**Comment by bastibl** [comment]
Thanks for bringing this up. I'm not very familiar with maintaining Android apps, but for me it seems as if the Gradle version is specified in the app:
https://github.com/bastibl/android-benchmark/blob/master/build.gradle#L11

I'd assume you manually upgraded (probably through the IDE) to a new major version with breaking changes. Or did this happen automatically?

I could try to chase the most recent version of the many tool of the Android build system, but I'm not sure if this is the best approach in the long run.
