### ISSUE TITLE
lower android api version

### ISSUE THREAD

**Issue by martinspears** [bastibl/gnuradio-android#5]
is there a way of getting this into a slightly lower android api version say 8.1.0???

**Comment by bastibl** [comment]
Not sure if there is a confusion between Android versions and API versions. At the moment the provided applications target API version 29. It should be possible to reduce it to 26 without problems. Android version 8.1 uses API version 27, so this shouldn't be an issue. Did you experience any problems?

**Comment by martinspears** [comment]
no not yet, I just wanted to make certain, I I checked my android device prior to installation process

**Comment by bastibl** [comment]
Ah, OK. I only had a phone with API level 29, so I used it but didn't try any other versions. If you give it a shot, it would be interesting to know, if itworked out of the box or if you had any issues. (I wouldn't expect any issues for >=26, but I didn't test it.)
