### ISSUE TITLE
open-ssl

### ISSUE THREAD

**Issue by qinchuanhui** [bastibl/gnuradio-android#6]
The open-ssl submodule cannot be cloned into in the repository.
Would you please update it ? Thanks a lot.

**Comment by bastibl** [comment]
I'm not sure what you mean. This project links to `git://git.openssl.org/openssl.git`. See here: https://github.com/bastibl/gnuradio-android/blob/master/.gitmodules#L10-L12
I just tried to clone from this repository and it works fine. It's also the main repository listed on the OpenSSL website: https://www.openssl.org/source/gitrepo.html

**Comment by qinchuanhui** [comment]
It's my fault,  and I have solved that, thanks a lot.
