### ISSUE TITLE
Is it able to run it on a virtual device in the android studio?

### ISSUE THREAD

**Issue by NeutrinoLiu** [bastibl/gnuradio-android#7]
with the SDR connect to PC's usb port

**Comment by bastibl** [comment]
That's an interesting idea. I'm not an expert for Android development and it didn't even came to my mind to try this. If you happen to have some time to try this, I'd be very interested.

If you are looking for ADB debugging while having an SDR connected, you can try this:
https://developer.android.com/guide/topics/connectivity/usb#debug-considerations
