### ISSUE TITLE
fail in build docker img

### ISSUE THREAD

**Issue by NeutrinoLiu** [bastibl/gnuradio-android#8]
after running `docker build -t gnuradio-android .`
it fails in the 5th step "apt-get update"
![Screen Shot 2020-12-29 at 9 15 00 PM](https://user-images.githubusercontent.com/24238886/103327622-eb2afc00-4a1a-11eb-80f3-0976993bf313.png)
wondering do you have similar issue

**Comment by NeutrinoLiu** [comment]
this is what i get from [askubuntu](https://askubuntu.com/questions/1299440/ubuntu-eoan-release-does-not-have-a-release-file), they say "eoan is EoL". any idea how to solve the issue? 
Or can I directly **change the docker distro to ubuntu 18LTS or some other distro**. I am not sure about the compatibility.

[update] well I use ubuntu 18.04 instead of 19, everything works fine currently.

**Comment by bastibl** [comment]
Thanks for the info. I should probably have used an LTS version :-) For now, I changed the sources:

https://github.com/bastibl/gnuradio-android/commit/862f4d552e30a34998311681382367bda167f157
