### ISSUE TITLE
Adalm-pluto support?

### ISSUE THREAD

**Issue by fpgasdr** [bastibl/gnuradio-android#9]
Hello,
I have this board and would like to try with this environment. it's possible?.

**Comment by bastibl** [comment]
It's certainly possible, but it's not totally trivial, as you'd have to cross-compile `gr-iio` and its dependencies. (IIRC, `libad9361` and `libiio`). I didn't try to cross-compile these projects. Some just work and some require fiddling with the build system.

**Comment by fpgasdr** [comment]
Thanks,
just curious and seems hard to do (at least for me since not have enough background in cross compile for android).
